### ISSUE TITLE
Cannot Install on Windows through NPM

### ISSUE THREAD

**Issue by lggarrison** [qrohlf/trianglify#102]
Windows doesn't support the `canvas` dependency.

I got around this issue by forking the repo and removing the dependency.

**Comment by andest01** [comment]
Seems like it wanted to install `cairo` via gyp. It failed. Forking fixed it.

**Comment by qrohlf** [comment]
canvas is listed as an optionalDependency, you should be able to install Trianglify without canvas support on Windows. You'll see warnings when running npm install, but it is [as the npm team intended](http://npm.github.io/using-pkgs-docs/package-json/types/optionaldependencies.html).
