### ISSUE TITLE
The canvas module is outdated

### ISSUE THREAD

**Issue by manuth** [qrohlf/trianglify#112]
The major version of your canvas-dependency is outdated (current is `2.x.x`).
The outdated version (`^1.3.0`) cannot be installed with the most recent LTS-version of npm.

Could you please update the dependency?

**Comment by qrohlf** [comment]
@manuth this is planned for the upcoming 3.0 release, in the meantime you should be able to install the dev branch with `npm install trianglify@next`

**Comment by qrohlf** [comment]
Note: I just released `v3.0.0` today, based on the `v2.0.0` codebase. It includes support for the latest version of node-canvas, as well as support for node 10 (previously, I was compiling with node 4 😬)

The `next` branch, which is more of a ground-up rewrite, will likely be released as `v4.0.0`, stay tuned for updates!
