### ISSUE TITLE
Option to Choose Color Format

### ISSUE THREAD

**Issue by AriGibson** [qrohlf/trianglify#114]
Regarding [this commit last year](https://github.com/qrohlf/trianglify/commit/b2b3e89e8d3e4c34e2025f18fb6258e2619d4b8b):

I think it would be nice if there was an option to choose whether to use hex or rgb color formats. It's not a huge deal, but the extra bytes used for rgb opposed to hex seem unnecessary and add up over time. Was there a reason for swapping to rgb?

Unrelated but very minor, package.json still shows version 1.3.0. 😛 

I really appreciate the work and would help if I knew how... thank you so much! 😊

**Comment by qrohlf** [comment]
The swapping to RGB(A) was to allow for alpha transparency, which isn't possible with hex codes.

Regarding versioning, my efforts are currently going towards a `v3.0.0` release, you can see progress on this version in the `next` branch and this issue: https://github.com/qrohlf/trianglify/issues/111

The primary goal of v3 is to modernize the codebase, and to allow for more advanced customization of the output. The SVG generation in v3 should allow you to pick the color format that's being used.

**Comment by AriGibson** [comment]
Awesome, that totally makes sense. I know `#RRGGBBAA` (Hex8) is supported in Chrome and Firefox; hoping that becomes more popular in the future. I appreciate your effects and am hoping to submit some examples or contribute in any other way, because this library is so valuable for pretty, dynamic designs. 👍 😀 

With the versioning, I've been keeping track of that release and am excited. I should've been more clear, my bad. In the current [package.json on line 3](https://github.com/qrohlf/trianglify/blob/cbb4ccb4295b820fb1d26dfabb585d047f2afafe/package.json#L3), the version is still listed as `1.3.0` instead of `2.0.0`. Didn't make sense to propose a change for a little typo like that; figured I'd let you know though.

Thanks for the effort!
