### ISSUE TITLE
Passing destSVG to pattern.toSVG() does not work; implementation is missing 🤦‍♂️

### ISSUE THREAD

**Issue by IsakUlstrup** [qrohlf/trianglify#134]
From the docs: 

> If an existing svg element is passed as the destSVG, this function will render the pattern to the pre-existing element instead of creating a new one.

The way I understand it, the attached code should work, but it doesn't.
In fact it doesn't seem like passing destSVG does anything. Am I missing something?

[codePen](https://codepen.io/isakUlstrup/pen/Vwjpwqx)

**Comment by qrohlf** [comment]
@IsakUlstrup - you're right, I just looked at the code and the implementation for destSVG is completely missing. I think I accidentally deleted it when I refactored some of the SVG serialization code!

I'll update and push a new version soon. In the mean time, you'll need to make do without destSVG!

**Comment by qrohlf** [comment]
TODO list:
- [ ] Implement missing functionality 
- [ ] write tests
- [ ] add an example to the examples folder
- [ ] review documentation for accuracy
- [ ] cut a point release

**Comment by IsakUlstrup** [comment]
Cool, thanks!

**Comment by qrohlf** [comment]
@IsakUlstrup got the implementation done ([very easy change](https://github.com/qrohlf/trianglify/pull/135/commits/c19118fac4d12cbe759c7eba8e918d7b4fe10602#diff-efef280387c5035ce74d6df1aa4d314aacb0d00232c861e7153243e5738a5354)), still need to write tests before I merge it though.

In the mean time, you can `npm install --save trianglify@next` and that'll get you going with the fixed code.

**Comment by qrohlf** [comment]
This is now available in `master` (`npm install --save trianglify@4.1.1`)
