### ISSUE TITLE
minimum custom D3 build for trianglify to depend on

### ISSUE THREAD

**Issue by tmaslen** [qrohlf/trianglify#25]
Hi,

Really loving trianglify, thanks for making it!  Do you know what the minimum build of D3 needs to be to make it work with trianglify?  Right now I've identified the modules:

* core
* selection
* scale
* interpolate
* geom

Would be a nice feature to list or even provide the minimum D3 build required to run trianglify, as the lib progresses I'd imagine the custom build may change.

Thanks,
/t

**Comment by qrohlf** [comment]
Closing this as the upcoming v0.2.0 release will get rid of the d3 dependency entirely in favor of ironwallaby/delaunay and vanilla JS for SVG/canvas/etc.

**Comment by NiklasBr** [comment]
> upcoming v0.2.0 release will get rid of the d3 dependency

[bower.json](https://github.com/qrohlf/trianglify/blob/master/bower.json) still lists d3 as a requirement, what happened?

**Comment by qrohlf** [comment]
I forgot to update bower.json :/

Will fix and issue a patch on Monday.

**Comment by qrohlf** [comment]
@NiklasBr I just pushed `v0.3.1` which removes d3 as a dependency in `bower.json` and also updates the `main` entry to point to the right location. 

TBH I kind of forgot that people used bower. I guess I've had my head stuck in the node ecosystem for too long lately.

**Comment by NiklasBr** [comment]
Thanks! 👍

I'm just getting started with node so I don't know any better :)
