### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by e-jigsaw** [qrohlf/trianglify#36]
![2015-04-21 1 28 12](https://cloud.githubusercontent.com/assets/557961/7234925/c0a3f88c-e7c5-11e4-9f50-758a08b8b702.png)

Google Chrome 42.0.2311.90

**Comment by qrohlf** [comment]
Thanks for letting me know! What OS are you using? That section of the
pages uses css3 columns, which are sometimes weird across platforms.

**Comment by e-jigsaw** [comment]
OSX 10.9.5

**Comment by qrohlf** [comment]
Looks like the gpu-rendered canvas elements were completely ignoring the CSS3 multi-column layout, in a totally bizarre yet typical example of why CSS sucks. Fixed by switching to floats.

Relevant: http://research.microsoft.com/en-us/people/mickens/ToWashItAllAway.pdf

**Comment by e-jigsaw** [comment]
:clap:
