### ISSUE TITLE
Typos in example

### ISSUE THREAD

**Issue by kozzles** [qrohlf/trianglify#37]
Love the package! Minor typo on the landing page example missing two commas:

var defaults = {
  cell_size: 75,
  variance: 0.75,
  x_colors: 'random',
  y_colors: 'match_x'
  palette: Trianglify.colorbrewer,
  color_space: 'lab'
  color_function: false,
  stroke_width: 1.51,
  width: 600,
  height: 400,
  seed: null
};

should be:

var defaults = {
  cell_size: 75,
  variance: 0.75,
  x_colors: 'random',
  y_colors: 'match_x',
  palette: Trianglify.colorbrewer,
  color_space: 'lab',
  color_function: false,
  stroke_width: 1.51,
  width: 600,
  height: 400,
  seed: null
};

**Comment by qrohlf** [comment]
Thanks, will fix asap.
