### ISSUE TITLE
Create Seamless pattern 

### ISSUE THREAD

**Issue by manatarms** [qrohlf/trianglify#39]
Is there any way to create a seamless pattern that can be tiled horizontally? What will I need to change? Thanks

**Comment by tdhsmith** [comment]
The triangulation is completely determined by the position of the points, so it should work just to take the points near the left and right edges and duplicate them on the opposite sides (one cell size beyond where the current points are).  You'll have to get rid of the existing horizontal bleed or you won't see the part where it "connects". And you'll have to restrict the cell_size to a divisor of the width, or the connection won't look right.

**Comment by qrohlf** [comment]
What @tdhsmith said. You'll also want to provide a custom color_function, since the gradient won't really tile well.
