### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by adrianoresende** [qrohlf/trianglify#46]
HTML
`<canvas id="canvas"></canvas>`
Javascript
`pattern.canvas($('#canvas'))`

Error:
`Uncaught TypeError: o.setAttribute is not a function`

Why not have support for jQuery?

**Comment by qrohlf** [comment]
Because Trianglify supports DOM nodes, not jQuery selections (which happen to be arrays, so it wouldn't even make sense to pass that in to a call to pattern.canvas). Try it again with the underlying DOM node (you can get that easily from the jQuery selection).
