### ISSUE TITLE
Is it possible to make a border background using trianglify?

### ISSUE THREAD

**Issue by Zorig** [qrohlf/trianglify#54]
I'm trying to make a polygonal div with trianglify background, and polygonal shape is created by css borders. Now i need to trianglify the background of borders is it possible?

**Comment by qrohlf** [comment]
Yes, it is possible.

**Comment by Zorig** [comment]
@qrohlf how? i'm trying to make it work on this div [link](https://jsfiddle.net/zorig/yqu709fu/2/) the hexagon is made by css border.
