### ISSUE TITLE
trianglify generated image as a div's background?

### ISSUE THREAD

**Issue by ser** [qrohlf/trianglify#58]
Hi,
is it possible to make trianglify generated image as a div's background? If yes, how? Code similar to:

```
<div class="fullscreen background" style="background-image:url('http://www.minimit.com/images/picjumbo.com_IMG_6648.jpg');" data-img-width="1600" data-img-height="1064">
```

**Comment by HtTYDDS** [comment]
I'd suggest you actually just output the generated image as a PNG data url and set that as the diva background via a CSS update. I can comment my code that I use for this if you'd like.

**Comment by hyperreal-info** [comment]
If you could provide some code, I would be really grateful, and I think not only me :)
Thanks!

**Comment by ser** [comment]
If you could provide some code, I would be really grateful, and I think not only me :)
Thanks!

**Comment by HtTYDDS** [comment]
**This shows how to add the trianglify generated image as a base64 png as a background image to anything with the class of background.**
_You can of course edit the insert rule to use identifiers instead of classes if you'd like to be more specific. Adding this inside of a document load function will make it run on load._ 
```
<div class="fullscreen background"></div>

<script>
var pattern = Trianglify({
  width: 1600,
  height: 1064,
  cell_size: 300 + Math.random() * 1000,
  x_colors: ['#111', '#111', '#000'],
  y_colors: ['#111', '#333', '#222'],
  stroke_width: 3
}).png();
var pattern64 = pattern.substr(pattern.indexOf('base64') + 7);

var sheet = (function() {
  var style = document.createElement("style");
  
  style.appendChild(document.createTextNode(""));
  
  document.head.appendChild(style);
  
  return style.sheet;
})();
sheet.insertRule(".background { background: transparent url(data:image/png;base64,"+pattern64+"); }", 0.5);
}
</script>
```

**Comment by qrohlf** [comment]
closing as solved unless @ser says otherwise

**Comment by ser** [comment]
I'm really sorry that I forgot to say thank you! It works fantastically.

**Comment by HtTYDDS** [comment]
Of course :) I'm glad I could help. Thanks to qrohlf for the amazing library.
