### ISSUE TITLE
Animation?

### ISSUE THREAD

**Issue by kunkinkan** [qrohlf/trianglify#60]
Any chance for animation for this?
- Movement
- Color changes.

**Comment by qrohlf** [comment]
@kunkinkan I've been playing with some ideas on this, actually. They're not ready for the prime-time yet, but you can expect an announcement on the repo when they are.

**Comment by chapterjason** [comment]
+1 would be awesome!

**Comment by AlexandreBonaventure** [comment]
I forked your library (forked from https://github.com/enzuguri/trianglify) for animation purpose. 

There is an example here: https://github.com/LichenInc/trianglify/blob/expose_generic_render_function/examples/animation-example.html

Hope it will inspire some of you. Cheers !

**Comment by dr-dimitru** [comment]
Hi all, I've done color animation at https://uniq.site
Let me know if you want to see used code.

**Comment by aycgit** [comment]
@dr-dimitru i would love to see that code

**Comment by dr-dimitru** [comment]
@aycgit 

To overview current settings type `_app.currentGradConfig` in console.

 1. Persistent seed - preserve how triangles is generated between animations
 2. Color transition is calculated by mixing colours via `tinycolor` npm package, which is randomly pick from pre-defined array. Then passed into `tetrad` method to get siblings colours
 3. `Trianglify(_app.currentGradConfig)` generates svg via `pattern.svg()` it is passed into the DOM only once.
 4. If svg is already at one I just change colours directly working with svg elements

Code responsible for color shift (*translated from CoffeeScript, sorry it's a bit ugly*):
```js
var _isGradRendered, _mbg, _svg, newChilds, oldChilds, pattern, svg;

_mbg = $('#mainBG');
pattern = Trianglify(_app.currentGradConfig);
svg = pattern.svg();

if (_mbg && _mbg.length) {
  if (_mbg.has('svg').length) {
    _svg = document.getElementById('mainBG').children[0];
    oldChilds = _svg.children;
    newChilds = svg.children;
    if (oldChilds.length === newChilds.length) {
      requestAnimationFrame(function() {
        var _attributes, attrName, j, k, newChild, newValue, oldChild;
        for (k in oldChilds) {
          oldChild = oldChilds[k];
          newChild = newChilds[k];
          _attributes = oldChild.attributes;
          if (_attributes && _attributes.length) {
            j = _attributes.length;
            while (j-- > 0) {
              attrName = _attributes[j].name;
              newValue = newChild.getAttribute(attrName);
              if (newValue !== _attributes[j].value) {
                oldChild.setAttribute(attrName, newValue);
              }
            }
          }
          return;
        }
      });
    } else {
      _mbg.html(svg);
      _isGradRendered = true;
    }
  } else {
    _mbg.html(svg);
    _isGradRendered = true;
  }
}
```

You may open DOM structure in a browser, see `#mainBG` in `body`, only colours of path's `fill` and `stroke` is changing.
And t's running in a loop of course.

**Comment by slzr** [comment]
Using TweenMax and the [Polylion](http://css-tricks.com/polylion) code I have this [simple result](http://codepen.io/jsalazart/pen/pjzOKb) with just few lines :smile:

**Comment by xBreaksx** [comment]
@slzr I dare you to do that but it makes random colors and designs instead of just the same thing over and over again

**Comment by Aysnine** [comment]
It's awesome, when will it be officially released？

**Comment by JenGL** [comment]
this is still not out yet ?

**Comment by qrohlf** [comment]
A quick note about the current state of animation in Trianglify - animation is likely not going to be included as a feature in the core Trianglify library. There are a few reasons for this:

- There are a (relatively) limited number of ways to configure a two-dimensional, static, colored Delaunay triangulation. There are virtually infinite ways to go about animating this stuff (point movement, color shifting, simulated depth like the [Flat Surface Shader](https://matthew.wagerfield.com/flat-surface-shader/) WebGL project, etc, and that's before you start to consider the various output formats (canvas animation, SVG, WebGL, pre-rendered WebM video, etc), all of which have their own pros/cons regarding bandwidth usage, CPU consumption, memory usage, etc. **The TL;DR is that I think trianglify animation is a large enough scope that it deserves its own project, repo, package, etc, and shouldn't be a part of Trianglify itself**
- The second practical reason for this is portability. Right now, Trianglify runs _fairly_ smoothly in both Node and Browsers, largely thanks to the small surface area where it talks to the DOM and the excellent node-canvas project. Extending Trianglify to start to include concepts like `window.requestAnimationFrame` or building on webGL primitives will make it much more difficult to support both node and browsers with the same codebase. 
- The final reason for this is that right now, Trianglify is a small and manageable project, and despite its relatively small size I _still_ often lack the time to properly update dependencies, review PRs, etc. I'm exploring some possible income streams that would allow me to devote more time to open-source work, but for now I'd like to continue to keep Trianglify as a simple, well-built, and responsibly-maintained single-maintainer project, and that means keeping scope and codebase size/complexity in a place where I feel comfortable.

If I do end up building out a new `trianglify-animation` package, you can expect an announcement on this thread. In the mean time, I suggest taking a look at the `pattern.polys` output data structure, which contains all the raw polygon and color data that you would need to extend the library and build your own trianglify animations - I look forward to seeing what the community can come up with!
