### ISSUE TITLE
Color generated

### ISSUE THREAD

**Issue by injectless** [qrohlf/trianglify#61]
Hi guys, amazing script.
I'm attempting to use this as a design background, and all the colors like being a extension of the colors that the background has each generation.

Like Ubuntu Unity. If the background is black, the toolbar is dark, if it's green, the toolbar takes the most used color to achieve a better mix.

I imagine how to do this, the problem is.. How can I get the generated colors (or most used, or a color inbetween) the background has used?

**Comment by qrohlf** [comment]
This issue tracker is for discussing bugs/issues with the Trianglify project. For general programming help like how to do palette generation from an image, http://stackoverflow.com/ is a much better fit for your question.
