### ISSUE TITLE
Rendering with limited radius

### ISSUE THREAD

**Issue by lapsio** [qrohlf/trianglify#63]
Is it possible to render angular shape instead of cropped rectangular canvas? I mean I'd like to render something like angular rectangle with shattered edges on transparent background not perfect rectangle. If it's not exposed but relatively quick patch I could probably patch it locally bc I'm a bit in rush.

**Comment by qrohlf** [comment]
Trianglify doesn't clip the bounds of the shapes it generates, it just sets the SVG bounds to mask them. If you render as SVG and manually adjust the viewBox so that the whole graphic is visible, you should be able to get an angular blob as output.

**Comment by lapsio** [comment]
Thank you :)
