### ISSUE TITLE
cdnjs version of trianglify cannot be used in a html page. 

### ISSUE THREAD

**Issue by maduhaime** [qrohlf/trianglify#68]
https://cdnjs.cloudflare.com/ajax/libs/trianglify/1.0.1/trianglify.js is not the version found in the dist folder.  It is the one from the lib folder.  If included in an html page, the following line will fault : 

var delaunay = require('delaunay-fast');

**Comment by qrohlf** [comment]
@maduhaime We no longer provide non-minified CDN builds for Trianglify. Use `trianglify.min.js` and it should work. CDNJS should not be publishing a non-minified file.
