### ISSUE TITLE
Replace delaunay-fast with delaunator

### ISSUE THREAD

**Issue by jhwohlgemuth** [qrohlf/trianglify#78]
I stumbled upon [Mapbox's](https://www.mapbox.com/) Delaunay implementation, [delaunator](https://github.com/mapbox/delaunator), a while ago and immediately thought of my favorite triangle drawing library.

Comparing the two implementations:
- Delaunator is [faster](https://github.com/mapbox/delaunator#performance)
- Delaunator is backed by Mapbox (presumably better support/longevity)
- Both have similar interfaces (I already have a [working fork with minimal changes](https://github.com/qrohlf/trianglify/compare/master...jhwohlgemuth:feature/replace-delaunay--fast-with-delaunator))

If you are interested, I will submit a PR.  If not, I still love trianglify! Thanks for sharing.

**Comment by qrohlf** [comment]
Mapbox makes awesome stuff, and it looks like the license is GPL-compatible so I see no issue with this. Feel free to spin up a PR!

**Comment by jhwohlgemuth** [comment]
@qrohlf 
[Pull request](https://github.com/qrohlf/trianglify/pull/81) ready for review.

**Comment by jhwohlgemuth** [comment]
Added with #81

**Comment by qrohlf** [comment]
This is now available on npm as `trianglify@v1.2.0`
