### ISSUE TITLE
Add noise variation to color

### ISSUE THREAD

**Issue by buckle2000** [qrohlf/trianglify#82]
![image](https://cloud.githubusercontent.com/assets/347189/6771063/f8b0af46-d090-11e4-8d4c-6c7ef5bd9d37.png)

Current colors are too uniform.

Maybe we can add random variation in addition to the palette and create something like this:

![default2](http://fc05.deviantart.net/fs70/f/2013/028/2/7/wallpaper_triangles_by_bhekman92-d5t130u.jpg)

**Comment by qrohlf** [comment]
@buckle2000 the library gives you the tools to do this, just pass in your own color function. Demo: https://codepen.io/anon/pen/GMXMox

**Comment by buckle2000** [comment]
Noice! Thanks for your work
