### ISSUE TITLE
Add support of transparent fill and stroke color options

### ISSUE THREAD

**Issue by pragmasoft-ua** [qrohlf/trianglify#84]
I'd want to create an svg background looking like an irregular mesh, maybe it's possible to achieve without changes of source code?

**Comment by EpicKris** [comment]
I'd like to see support for a custom stroke colour option.

**Comment by EpicKris** [comment]
I created a pull request #91 that adds an optional stroke colour, though this doesn't support transparency.

**Comment by qrohlf** [comment]
This is going to be included in v4, see below for a preview:

<img width="757" alt="Screen Shot 2020-04-22 at 12 41 46 PM" src="https://user-images.githubusercontent.com/347189/80026257-b7b0ce80-8496-11ea-867d-c4d476444c06.png">

**Comment by qrohlf** [comment]
This is supported in the latest release!

**Comment by Shpigford** [comment]
@qrohlf Is there a way to use stroke *in addition to* the fill? I'm essentially trying to outline the cells so each triangle has a border that, in this case, would be a different color than the fill (though all the strokes would be the same).
