### ISSUE TITLE
Additional settings for y_colors

### ISSUE THREAD

**Issue by Saucistophe** [qrohlf/trianglify#92]
I wanted to use simple vertical and horizontal gradients, without having to write a function.
Would you accept a PR in which : 

- y_colors can be an empty string, so that the output has an horizontal gradient based on x_colors;
- x_colors can be an empty string, so that the output has an horizontal gradient based on y_colors;
- both empty x_colors  and y_colors will yield an error

**Comment by qrohlf** [comment]
@Saucistophe this seems reasonable. The only suggestion I have is that instead of using empty string, I'd rather have the user pass `false` to signify that they don't want to have an x or y component to the gradient. 

Aside from that, I'd happily take that PR. Thanks for checking in!

**Comment by qrohlf** [comment]
closing this as resolved by #93, thanks @Saucistophe
