### ISSUE TITLE
The output image is cropped

### ISSUE THREAD

**Issue by Saucistophe** [qrohlf/trianglify#94]
I generated a pattern with the following:
`			let pattern = Trianglify({
				width: 350,
				height: 250,
				cell_size: 30,
				variance: 0.75,
				seed: null,
				x_colors: ['red','blue','yellow','purple','orange','green'],
				y_colors: ['white','black'],
				color_space: 'rgb',
				stroke_width: 0.6
			});
			var svg = pattern.svg();`

I was surprised to see that the red on the left and green on the right was so thin:
![image](https://user-images.githubusercontent.com/7082839/47118646-386e8900-d268-11e8-9000-45d498139b6d.png)

To check that further, I copied the generated svg into a file, set a broader viewBox (instead of the defaut, that would fit to the width and height and start in 0,0), and added a white rect that represents the default viewBox. Here is what I got:
![image](https://user-images.githubusercontent.com/7082839/47118430-846cfe00-d267-11e8-93f5-44573d2f4a43.png)

The white rectangle represents the part that is displayed, and you can see that some colors are cropped, and a good deal of triangles are lost.
I understand it's so that you don't have thin triangles on the border, or even holes; I also understand I can tweak it by duplicating colors at the extremities for instance; but I feel there must be a way to handle that nicely, maybe by making your gradient start on the inside of the box and not on the bounds of the outer triangles?

Steps to reproduce: Include the snippet above in a 350 * 250 box, and note that red and green extremities are out of the picture.

**Comment by qrohlf** [comment]
I agree with you that this isn't optimal, it's something I've wanted for fix for a while now. The real fix is to fix a set of points to the very edge of the viewbox, with one axis pinned so that variance is applied but only to the axis that's aligned with the edge the point is pinned to.

Unfortunately, I don't have a lot of time for this project at the moment, so it's unlikely I'll get around to fixing this. Feel free to take a stab at it in a PR! My only criteria is that the implementation needs to not cause any different aesthetic effects (smaller triangles, acute angles, etc) along the edges of the image, so you'll need to make sure that the cell grid is aligned properly with the edge-points.

**Comment by Saucistophe** [comment]
I've fixed the color cropping problem with simply two lines, by making the norm_x and norm_y _not_ take the external margins into account.
I end up from this:
![image](https://user-images.githubusercontent.com/7082839/47150035-9dac9380-d2d5-11e8-956f-c1ff1b79cef3.png)
...To this:
![image](https://user-images.githubusercontent.com/7082839/47150049-a735fb80-d2d5-11e8-9dfc-a7b952061ff5.png)

As before, the square represents the part that fits inside the default viewbox. As you can see, the red stars right on the edge of the square and goes on to the outside margins!

**Comment by qrohlf** [comment]
I still want to eventually get around to clipping the bleed shapes outside the viewBox, but for now I'm going to mark this specific issue as closed since your color problems are solved by #95. Release coming shortly!

**Comment by qrohlf** [comment]
@Saucistophe your fix is now out in `v1.3.0`, and it looks great.

**Before**
![trianglify-1 2 0](https://user-images.githubusercontent.com/347189/50549944-54ed5100-0c1b-11e9-804f-7bf6fb64bb51.png)

**After**
![trianglify-1 3 0](https://user-images.githubusercontent.com/347189/50549945-5ae33200-0c1b-11e9-91e8-72ecae791d18.png)
