### ISSUE TITLE
Generating Honeycombs instead of triangles

### ISSUE THREAD

**Issue by HeinzSchrot** [qrohlf/trianglify#96]
Hi,
is it possible to do a "honeycomb" version of trianglify? Which uses honeycombs of one specific size, instead of randomly sized triangles?

Thanks!

**Comment by qrohlf** [comment]
Right now, all of the rendering code and data structures set up for only 3 vertices, which is something I don't think makes sense to change for Trianglify.

That said, if you know JavaScript it would be pretty easy to whip up a one-off fork of Trianglify that just generates tiled hexagons with the same gradient based color function.
